<?php

namespace AppBundle\Repository;

/**
 * CahierdeschargesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CahierdeschargesRepository extends \Doctrine\ORM\EntityRepository
{
}
