<?php

namespace AppBundle\Repository;

/**
 * SocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
