app:
    resource: "@MyFOSUserBundle/Controller/"
    type:     annotation

my_fos_user_societe:
    resource: "@MyFOSUserBundle/Controller/SocieteController.php"
    type:     annotation

my_fos_user_user:
    resource: "@MyFOSUserBundle/Controller/UserController.php"
    type:     annotation 
    
my_fos_user_freelancer:
    resource: "@MyFOSUserBundle/Controller/FreelancerController.php"
    type:     annotation
    
my_fos_user.user.default_route:
    resource:  "@MyFOSUserBundle/Controller/UserController.php"
    type:       annotation
    
my_fos_user_user:
    resource: "@MyFOSUserBundle/Controller/UserController.php"
    type:     annotation

my_fos_user:
    path : /
    defaults: {_controller:MyFOSUserBundle:Default:index }
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    type:     xml







re_download:
    path : /dl/{file}
    defaults: {_controller:MyFOSUserBundle:Default:sendFile }
    
re_service:
    path: /service
    defaults: {_controller:MyFOSUserBundle:Default:service }
  
      
re_code:
    path: /code
    defaults: {_controller:MyFOSUserBundle:Default:code }
    
re_doc:
    path: /documentation
    defaults: {_controller:MyFOSUserBundle:Default:doc }    
    
re_fos_user:   
   path: /change-password
   defaults: {_controller:MyFOSUserBundle:MyChangePassword:changePassword }

re_fos_user_profile_show:
    path: /profil
    defaults: {_controller:MyFOSUserBundle:Profile:show }
 
re_fos_user_profile_edit: 
    path: /edit
    defaults: {_controller:MyFOSUserBundle:Profile:edit }

re_fos_user_registration_register:
    path: /registration
    defaults: {_controller:MyFOSUserBundle:Registration:register }
    
re_fos_user_registration_check_email:
    path: /check-email
    defaults: {_controller:MyFOSUserBundle:Registration:checkEmail }

re_fos_user_registration_confirm :
    path: /confirm/{token}
    defaults: {_controller:MyFOSUserBundle:Registration:confirm }
  
re_fos_user_registration_confirmed:
    path: /confirmed
    defaults: {_controller:MyFOSUserBundle:Registration:confirmed }



#    
#    <route id="fos_user_resetting_request" path="/request" methods="GET">
#        <default key="_controller">FOSUserBundle:Resetting:request</default>
#    </route>
#
#    <route id="fos_user_resetting_send_email" path="/send-email" methods="POST">
#        <default key="_controller">FOSUserBundle:Resetting:sendEmail</default>
#    </route>
#
#    <route id="fos_user_resetting_check_email" path="/check-email" methods="GET">
#        <default key="_controller">FOSUserBundle:Resetting:checkEmail</default>
#    </route>
#
#    <route id="fos_user_resetting_reset" path="/reset/{token}" methods="GET POST">
#        <default key="_controller">FOSUserBundle:Resetting:reset</default>
#    </route>
#
#
#    <route id="fos_user_resetting_request" path="/request" methods="GET">
#        <default key="_controller">FOSUserBundle:Resetting:request</default>
#    </route>
#
#    <route id="fos_user_resetting_send_email" path="/send-email" methods="POST">
#        <default key="_controller">FOSUserBundle:Resetting:sendEmail</default>
#    </route>
#
#    <route id="fos_user_resetting_check_email" path="/check-email" methods="GET">
#        <default key="_controller">FOSUserBundle:Resetting:checkEmail</default>
#    </route>
#
#    <route id="fos_user_resetting_reset" path="/reset/{token}" methods="GET POST">
#        <default key="_controller">FOSUserBundle:Resetting:reset</default>
#    </route>


#  

                #     GROUPS
#re_fos_user_group_list: 
#    path: /list
#    defaults: {_controller:MyFOSUserBundle:Group:list }

#
#re_fos_user_group_new:
#    path: /new
#    defaults: {_controller:MyFOSUserBundle:Group:new }

#    <route id="fos_user_group_show" path="/{groupName}" methods="GET">
#        <default key="_controller">FOSUserBundle:Group:show</default>
#    </route>
#
#    <route id="fos_user_group_edit" path="/{groupName}/edit" methods="GET POST">
#        <default key="_controller">FOSUserBundle:Group:edit</default>
#    </route>
#
#    <route id="fos_user_group_delete" path="/{groupName}/delete" methods="GET">
#        <default key="_controller">FOSUserBundle:Group:delete</default>
#    </route>
#    
