# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
      class: MyFOSUserBundle\Form\Type\RegistrationFormType
      tags:
          - { name: form.type, alias: app_user_registration }


    admin.category:
       class: MyFOSUserBundle\Admin\CategoryAdmin
       arguments: [~, MyFOSUserBundle\Entity\Category, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Category }
           
    admin.freelancer:
       class: MyFOSUserBundle\Admin\FreelancerAdmin
       arguments: [~, MyFOSUserBundle\Entity\Freelancer, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: FreelancerProfil }      
    
    admin.user:
       class: MyFOSUserBundle\Admin\UserAdmin
       arguments: [~, MyFOSUserBundle\Entity\User, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Utilisateurs }   

    admin.blogpost:
       class: MyFOSUserBundle\Admin\BlogPostAdmin
       arguments: [~, MyFOSUserBundle\Entity\BlogPost, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: BlogPost } 
           
    admin.cahierdescharges:
       class: MyFOSUserBundle\Admin\CahierdesChargesAdmin
       arguments: [~, MyFOSUserBundle\Entity\Cahierdescharges, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: CahierDesCharges } 
        
    admin.competence:
       class: MyFOSUserBundle\Admin\CompetenceAdmin
       arguments: [~, MyFOSUserBundle\Entity\Competence, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Competence } 
           
    admin.contrat:
       class: MyFOSUserBundle\Admin\ContratAdmin
       arguments: [~, MyFOSUserBundle\Entity\Contrat, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Contrat } 
    
    admin.message:
       class: MyFOSUserBundle\Admin\MessageAdmin
       arguments: [~, MyFOSUserBundle\Entity\Message, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Message } 
     
    admin.offre:
       class: MyFOSUserBundle\Admin\OffreAdmin
       arguments: [~, MyFOSUserBundle\Entity\Offre, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Offre } 
           
    admin.paiement:
       class: MyFOSUserBundle\Admin\PaiementAdmin
       arguments: [~, MyFOSUserBundle\Entity\Paiement, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Paiement } 
           
    admin.projet:
       class: MyFOSUserBundle\Admin\ProjetAdmin
       arguments: [~, MyFOSUserBundle\Entity\Projet, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Projet }       
           
    admin.societe:
       class: MyFOSUserBundle\Admin\SocieteAdmin
       arguments: [~, MyFOSUserBundle\Entity\Societe, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Societe }    
   
    admin.test:
       class: MyFOSUserBundle\Admin\TestAdmin
       arguments: [~, MyFOSUserBundle\Entity\Test, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Test }       
           
           