AppBundle\Entity\Admin:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AdminRepository
    id:
        idAdmin:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idUser:
            type: integer
            column: id_user
    lifecycleCallbacks: {  }
