AppBundle\Entity\Cahierdescharges:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CahierdeschargesRepository
    id:
        idCdc:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tarif:
            type: float
        delai:
            type: string
            length: 255
        idContrat:
            type: integer
            column: id_contrat
    lifecycleCallbacks: {  }
