AppBundle\Entity\Competence:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CompetenceRepository
    id:
        id_competence:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        categorie:
            type: string
            length: 255
        description:
            type: string
            length: 255
        id_freelancer:
            type: integer
            column: id_freelancer
    lifecycleCallbacks: {  }
