AppBundle\Entity\Message:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MessageRepository
    id:
        idMessage:
            type: integer
            id: true
            generator:
                strategy: AUTO
            column: id_message
    fields:
        id_freelancer:
            type: integer
            column: id_freelancer
        id_societe:
            type: integer
            column: id_societe
        type:
            type: string
            length: 255
        sujet:
            type: string
            length: 255
        contenu:
            type: string
            length: 255
        date:
            type: datetime
            length: 6
            column: date_sign
        idAdmin:
            type: integer
            column: id_admin
    lifecycleCallbacks: {  }
